Run command dr
Azure/Microsoft.AVS.Management pull request #198
Opened 2023-07-31 23:30 UTC by ankulkarni90

This PR closes #

The changes in this PR are as follows:

* Includes a cmdlet "Add-GroupToSRMAdmins" to add the group to the "SRM Administrators."
* Includes a cmdlet "Remove-GroupFromSRMAdmins" to remove the group from the "SRM Administrators."

I have read the [contributor guidelines](CONTRIBUTING.md) and have completed the following:

* [*] **Formatted the code** using VSCode default formatter for PowerShell.
* [*] **Tested the code** end-to-end against an SDDC.
* [*] **Documented the functions** using standard PowerShell markup and applied `AVSAttribute` to newly exported functions.

2023-08-01 16:59 UTC, jupatte commented
Also need to add to the "VRM Administrators" group as well.
That group will only exist if vSphere Replication was installed, but SRM in AVS currently requires vSphere Replication to be useful.

2023-08-30 13:40 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +        Write-Error "Unable to get external identity source" -ErrorAction Stop
Use `throw` instead, formatting the message with the original error from the excetion.

2023-11-10 17:05 UTC, jupatte approved these changes

2023-11-16 13:57 UTC, et1975 requested changes
I've asked Jay to consider moving SRM stuff into a separate internal package we discussed earlier. Let's sync up.

2023-11-16 13:57 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +        $SRMAdminMembers = Get-SsoGroup -Group $SRMAdmins -ErrorAction Continue
nit: ErrorAction is Continue by default, let's not add noise

2023-11-16 13:57 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +                Write-Error "Group $GroupName exists in multiple domains . Please re-run and specify domain" -ErrorAction Stop
Use `throw` instead of Write-Error with Stop

2024-04-12 13:30 UTC, et1975 commented
As discussed this will go into another repo.

2024-04-12 13:30 UTC, closed without merging