Update-IdentitySourceCertificates With No SAS
Azure/Microsoft.AVS.Management pull request #237
Opened 2024-02-01 00:56 UTC by Jiancao164

The changes in this PR are as follows:

* Parameter `SSLCertificatesSasUrl` in command `Update-IdentitySourceCertificates` is no longer mandatory. If `SSLCertificatesSasUrl` is not provided, it automatically downloads certificates from domain controllers to update. 

Test:
<img width="769" alt="image" src="https://github.com/Azure/Microsoft.AVS.Management/assets/60164697/33b59d66-aa70-44a1-9247-b1e586bffcc2">
![image](https://github.com/Azure/Microsoft.AVS.Management/assets/60164697/42cd8216-2a92-47a8-9691-10e09eacde41)

I have read the [contributor guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Formatted the code** using VSCode default formatter for PowerShell.
* [x] **Tested the code** end-to-end against an SDDC.
* [ ] **Documented the functions** using standard PowerShell markup and applied `AVSAttribute` to newly exported functions.

2024-02-01 15:06 UTC, et1975 requested changes
As a general comment, I think Get-Certificates and the new Save-Certificates are 2 versions of the same thing. I'd probably either reflect that in the name (download-from*) or combine them and based on parameters choose the strategy/source. Return the file names and pipe that into vcenter call.

2024-02-02 00:25 UTC, Jiancao164 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +            $ParsedUrl = [System.Uri]$computerUrl
Hope I have addressed your comment.

2024-02-02 13:51 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +        $ResultUrl = $ParsedUrl.Scheme + '://' + $ParsedUrl.Host + ':' + $ParsedUrl.Port
There's an [existing method](https://learn.microsoft.com/en-us/dotnet/api/system.uri.getleftpart?view=net-8.0#remarks) for this.

2024-02-02 13:53 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +            throw "Incorrect Url format. $computerUrl is an IP address. Consider using hostname exactly as specified on the issued certificate."
Should probably change the wording, "consider" seems like a mild suggestion while in reality it is the exact requirement.

2024-02-02 13:54 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +            throw "Incorrect Url format entered from: $computerUrl"
It's more helpful to state what the actual expectation is than to say the input is wrong.

2024-02-05 15:38 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +        $ResultUrl = $ParsedUrl.GetLeftPart('Authority')
Does using string work? I'd expect the parameter to be enum, so `[UriPartial]::Authority`

2024-02-06 14:30 UTC, et1975 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +function Get-CertificateFromDomainContollerToLocalFile {
Let's not use Domain Controller - yes, it's a most common type of LDAP customers have, but that's not the defining characteristic of it - we don't if it's a DC in the slightest, it just needs to be TLS-protected LDAP server.
It's also mispelled.

2024-02-06 19:11 UTC, Jiancao164 commented on Microsoft.AVS.Management/Microsoft.AVS.Management.psm1
> +    $exportFolder = "$home/"
Seems at least in the testing environment `[System.Security.Cryptography.X509Certificates.X509Certificate2]::CreateFromCertFile($certfilePath)` can only take absolute path, relative path not working.

2024-02-06 20:34 UTC, et1975 approved these changes

2024-02-06 20:35 UTC, merged